version: '3.7'
services:
  db:
    image: postgres:12.2-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - common-network
    
  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      SECRET_KEY_BASE: gw/XX0eYX32DsPtP0szJmOIY+5yCsuTXTMcd1Nwl3jE8/9/qAbrHuXLKdElcRpXe
      HOST_NAME: localhost
    ports:
      - 4000:4000
    networks:
      - common-network

volumes:
  db-data:

networks:
  common-network:
    driver: bridge